### ISSUE TITLE
`prefix_min_len` obsolete, since blink.cmp's `min_keyword_length` takes care of that

### ISSUE THREAD

**Issue by chrisgrieser** [niuiic/blink-cmp-rg.nvim#3]
Not a dealbreaker, but `prefix_min_len` is basically obsolete since blink.cmp added `min_keyword_length` in the last update, since the minimum prefix length is overridden now anyway. For the sake of simplification, the `prefix_min_len` should probably be removed?

**Comment by niuiic** [comment]
`blink.cmp` gets prefixes in a different way, thus `min_keyword_length` may not be what you want. I tried this option and it did not work as expected.

**Comment by chrisgrieser** [comment]
Hmm yeah. Though there is nonetheless some interaction between the two, e.g. using `prefix_min_len = 3` and `min_keyword_length = 4`, results in rg results only being displayed when typing 4 characters.

**Comment by niuiic** [comment]
Just unset `min_keyword_length`, that is out of control of a source.
